### ISSUE TITLE
Not installable from public NPM?

### ISSUE THREAD

**Issue by alexkrolick** [dollarshaveclub/react-passage#4]
```
yarn add @dollarshaveclub/react-passage
yarn add v1.12.1
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.npmjs.org/@dollarshaveclub%2freact-passage: Not found".
```

**Comment by yowainwright** [comment]
@alexkrolick damn. Thanks for pointing this out!!!

**Comment by arjansingh** [comment]
Yes, our apologies for the oversite. We're working on this now.

**Comment by yowainwright** [comment]
@alexkrolick thanks so much for pointing this out! 

Sorry for the time it took for us to notice this issue.

----

The good news is—this issue has bee resolved thanks mainly to @kylecorbelli! 

* [@dollarshaveclub/react-passage](https://www.npmjs.com/package/@dollarshaveclub/react-passage) is now public
